# Generated by Django 5.1.2 on 2025-02-21 03:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0022_botvernacular_alt_introductory_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBotTCRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_model', models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct')], default='gpt-4o-mini', max_length=100)),
                ('provider', models.CharField(choices=[('bedrock', 'BEDROCK'), ('bedrock/converse', 'BEDROCK_CONVERSE'), ('openai', 'OPENAI')], default='openai', max_length=100)),
                ('status', models.CharField(choices=[('running', 'RUNNING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='running', max_length=100)),
                ('metrics_result', models.TextField(blank=True, null=True)),
                ('company_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.companybot')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBotTestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_input', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('retrieval_context', models.TextField(blank=True, null=True)),
                ('input_format', models.CharField(choices=[('json', 'JSON'), ('text', 'TEXT')], default='json', max_length=100)),
                ('json_output_schema', models.TextField(blank=True, null=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession')),
                ('company_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.companybot')),
            ],
        ),
        migrations.CreateModel(
            name='BotRunTestCaseMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('answer_relevancy', 'ANSWER_RELEVANCY'), ('faithfullness', 'FAITHFULLNESS'), ('contextual_precision', 'CONTEXTUAL_PRECISION'), ('contextual_recall', 'CONTEXTUAL_RECALL'), ('contextual_relevancy', 'CONTEXTUAL_RELEVANCY'), ('bias', 'BIAS'), ('toxicity', 'TOXICITY'), ('summarization', 'SUMMARIZATION'), ('prompt_allignment', 'PROMPT_ALLIGNMENT'), ('hallucination', 'HALLUCINATION'), ('json_correctness', 'JSON_CORRECTNESS')], max_length=100)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pass', 'PASS'), ('failed', 'FAILED')], max_length=100, null=True)),
                ('bot_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observability.companybottcrun')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observability.companybottestcases')),
            ],
        ),
        migrations.CreateModel(
            name='TCBotRunMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('answer_relevancy', 'ANSWER_RELEVANCY'), ('faithfullness', 'FAITHFULLNESS'), ('contextual_precision', 'CONTEXTUAL_PRECISION'), ('contextual_recall', 'CONTEXTUAL_RECALL'), ('contextual_relevancy', 'CONTEXTUAL_RELEVANCY'), ('bias', 'BIAS'), ('toxicity', 'TOXICITY'), ('summarization', 'SUMMARIZATION'), ('prompt_allignment', 'PROMPT_ALLIGNMENT'), ('hallucination', 'HALLUCINATION'), ('json_correctness', 'JSON_CORRECTNESS')], max_length=100)),
                ('assessment_questions', models.TextField(blank=True, null=True)),
                ('metric_threshold_value', models.FloatField(default=0.7, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('metric_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(blank=True, null=True)),
                ('bot_tc_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observability.companybottestcases')),
            ],
        ),
    ]
