# Generated by Django 5.1.2 on 2025-02-26 10:01

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0023_companybot_provider_companybot_provider_keys_and_more'),
        ('observability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBotRunTestCaseMap',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('answer_relevancy', 'ANSWER_RELEVANCY'), ('faithfullness', 'FAITHFULLNESS'), ('contextual_precision', 'CONTEXTUAL_PRECISION'), ('contextual_recall', 'CONTEXTUAL_RECALL'), ('contextual_relevancy', 'CONTEXTUAL_RELEVANCY'), ('bias', 'BIAS'), ('toxicity', 'TOXICITY'), ('summarization', 'SUMMARIZATION'), ('prompt_allignment', 'PROMPT_ALLIGNMENT'), ('hallucination', 'HALLUCINATION'), ('json_correctness', 'JSON_CORRECTNESS')], max_length=100)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pass', 'PASS'), ('failed', 'FAILED')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical bot run test case map',
                'verbose_name_plural': 'historical bot run test case maps',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompanyBotTCRun',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('llm_model', models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct')], default='gpt-4o-mini', max_length=100)),
                ('provider', models.CharField(choices=[('bedrock', 'BEDROCK'), ('bedrock/converse', 'BEDROCK_CONVERSE'), ('openai', 'OPENAI')], default='openai', max_length=100)),
                ('status', models.CharField(choices=[('running', 'RUNNING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='running', max_length=100)),
                ('metrics_result', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical company bot tc run',
                'verbose_name_plural': 'historical company bot tc runs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompanyBotTestCases',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('testcase_input', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('retrieval_context', models.TextField(blank=True, null=True)),
                ('input_format', models.CharField(choices=[('json', 'JSON'), ('text', 'TEXT')], default='json', max_length=100)),
                ('json_output_schema', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical company bot test cases',
                'verbose_name_plural': 'historical company bot test casess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='botruntestcasemap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='botruntestcasemap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='companybottestcases',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companybottestcases',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='botruntestcasemap',
            index=models.Index(fields=['bot_run'], name='observabili_bot_run_4cf0f4_idx'),
        ),
        migrations.AddIndex(
            model_name='botruntestcasemap',
            index=models.Index(fields=['metric_name'], name='observabili_metric__8cb07c_idx'),
        ),
        migrations.AddIndex(
            model_name='companybottestcases',
            index=models.Index(fields=['company_bot'], name='observabili_company_8afb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='companybottestcases',
            index=models.Index(fields=['created_at'], name='observabili_created_7c2e52_idx'),
        ),
        migrations.AddIndex(
            model_name='companybottestcases',
            index=models.Index(fields=['chat_session'], name='observabili_chat_se_d06d4c_idx'),
        ),
        migrations.AddField(
            model_name='historicalbotruntestcasemap',
            name='bot_run',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='observability.companybottcrun'),
        ),
        migrations.AddField(
            model_name='historicalbotruntestcasemap',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbotruntestcasemap',
            name='test_case',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='observability.companybottestcases'),
        ),
        migrations.AddField(
            model_name='historicalcompanybottcrun',
            name='company_bot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot'),
        ),
        migrations.AddField(
            model_name='historicalcompanybottcrun',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompanybottestcases',
            name='chat_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.chatsession'),
        ),
        migrations.AddField(
            model_name='historicalcompanybottestcases',
            name='company_bot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot'),
        ),
        migrations.AddField(
            model_name='historicalcompanybottestcases',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
