# Generated by Django 5.1.2 on 2025-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0002_historicalbotruntestcasemap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybottestcases',
            name='about',
            field=models.TextField(blank=True, help_text='Optional description of the test case. For informational purposes only; it does not affect the test output.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanybottestcases',
            name='about',
            field=models.TextField(blank=True, help_text='Optional description of the test case. For informational purposes only; it does not affect the test output.', null=True),
        ),
    ]
