# Generated by Django 5.1.2 on 2025-04-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0003_companybottestcases_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botruntestcasemap',
            name='response_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbotruntestcasemap',
            name='response_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
