# Generated by Django 5.1.2 on 2024-10-28 08:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('category_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shikshalokam"."category',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('category_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical category',
                'verbose_name_plural': 'historical categorys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProjectTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.category')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project template',
                'verbose_name_plural': 'historical project templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_id', models.CharField(max_length=255, unique=True)),
                ('recommended_for', models.CharField(blank=True, max_length=400, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('STARTED', 'STARTED'), ('inPROGRESS', 'inPROGRESS'), ('SUBMITTED', 'SUBMITTED')], max_length=100, null=True)),
                ('other_params', models.JSONField(blank=True, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('resource_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('project_start_date', models.DateTimeField(blank=True, null=True)),
                ('project_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='chatbot.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='chatbot.story')),
            ],
            options={
                'db_table': 'shikshalokam"."project',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('parent_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('mandatory_task', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('observation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_submission_observation', models.IntegerField(blank=True, null=True)),
                ('other_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.project')),
            ],
            options={
                'verbose_name': 'historical task',
                'verbose_name_plural': 'historical tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_template', to='shikshalokam.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shikshalokam"."project_template',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='shikshalokam.projecttemplate'),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('recommended_for', models.CharField(blank=True, max_length=400, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('STARTED', 'STARTED'), ('inPROGRESS', 'inPROGRESS'), ('SUBMITTED', 'SUBMITTED')], max_length=100, null=True)),
                ('other_params', models.JSONField(blank=True, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('resource_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('project_start_date', models.DateTimeField(blank=True, null=True)),
                ('project_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.profile')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.story')),
                ('project_template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.projecttemplate')),
            ],
            options={
                'verbose_name': 'historical project',
                'verbose_name_plural': 'historical projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('mandatory_task', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('observation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_submission_observation', models.IntegerField(blank=True, null=True)),
                ('other_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='shikshalokam.project')),
            ],
            options={
                'db_table': 'shikshalokam"."task',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvidence',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('evidence_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.project')),
                ('task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.task')),
            ],
            options={
                'verbose_name': 'historical evidence',
                'verbose_name_plural': 'historical evidences',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('evidence_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='shikshalokam.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='shikshalokam.task')),
            ],
            options={
                'db_table': 'shikshalokam"."evidence',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_name_d601b7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_id'], name='category_categor_ad40b9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='category_created_74b871_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['title'], name='project_tem_title_c77d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['template_id'], name='project_tem_templat_c85469_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['created_at'], name='project_tem_created_6217eb_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['category'], name='project_tem_categor_5a668d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='project_title_8f019f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_id'], name='project_project_a46baf_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['recommended_for'], name='project_recomme_f0b0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['keywords'], name='project_keyword_2c9b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['objective'], name='project_objecti_8fdb4d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['duration'], name='project_duratio_798967_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_status'], name='project_project_4ef16a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['resource_name'], name='project_resourc_c93ada_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_start_date'], name='project_project_ffec82_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_end_date'], name='project_project_7d2439_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='project_created_86fac0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['story'], name='project_story_i_3d895c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_template'], name='project_project_d9c951_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['author'], name='project_author__80fdfd_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent_task_id'], name='task_parent__050910_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_id'], name='task_task_id_d6360f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_name'], name='task_task_na_f244c5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['mandatory_task'], name='task_mandato_0ac874_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['observation_name'], name='task_observa_7b3d09_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['number_of_submission_observation'], name='task_number__e776f7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='task_created_fe28b4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='task_project_c9b488_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['remark'], name='evidence_remark_71486e_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['evidence_link'], name='evidence_evidenc_19d5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['created_at'], name='evidence_created_507292_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['task'], name='evidence_task_id_6d7c86_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['project'], name='evidence_project_12e816_idx'),
        ),
    ]
