# Generated by Django 5.1.2 on 2025-02-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshalokam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
