# Generated by Django 5.1.2 on 2025-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshalokam', '0002_historicalproject_problem_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='actual_duration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='actual_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='actual_problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='actual_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='expected_duration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='expected_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='expected_problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='expected_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_duration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_duration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
