# Generated by Django 5.1.2 on 2025-02-20 10:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_remove_companybot_max_token_and_more'),
        ('shikshalokam', '0003_historicalproject_actual_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLearningResources',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=500, null=True)),
                ('app', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical learning resources',
                'verbose_name_plural': 'historical learning resourcess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProjectVernacular',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('language', models.CharField(max_length=250)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical project vernacular',
                'verbose_name_plural': 'historical project vernaculars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProjectWishlist',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical project wishlist',
                'verbose_name_plural': 'historical project wishlists',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LearningResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=500, null=True)),
                ('app', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shikshalokam"."learning_resource',
            },
        ),
        migrations.CreateModel(
            name='ProjectVernacular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=250)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shikshalokam"."project_vernacular',
            },
        ),
        migrations.CreateModel(
            name='ProjectWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shikshalokam"."project_wishlist',
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalevidence',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='generated_by',
            field=models.CharField(choices=[('AI_GENERATED', 'AI_GENERATED'), ('EXPERT_VETTED', 'EXPERT_VETTED')], default='AI_GENERATED', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='program_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='program_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='program_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='project_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='project_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='template_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='task_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='generated_by',
            field=models.CharField(choices=[('AI_GENERATED', 'AI_GENERATED'), ('EXPERT_VETTED', 'EXPERT_VETTED')], default='AI_GENERATED', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='program_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='program_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='program_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='template_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_id',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('STARTED', 'STARTED'), ('inPROGRESS', 'inPROGRESS'), ('SUBMITTED', 'SUBMITTED'), ('PUBLISHED', 'PUBLISHED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='recommended_for',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='chatbot.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('STARTED', 'STARTED'), ('inPROGRESS', 'inPROGRESS'), ('SUBMITTED', 'SUBMITTED'), ('PUBLISHED', 'PUBLISHED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='recommended_for',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['actual_title'], name='project_actual__583ea5_idx'),
        ),
        migrations.AddField(
            model_name='historicallearningresources',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallearningresources',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallearningresources',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.project'),
        ),
        migrations.AddField(
            model_name='historicalprojectvernacular',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprojectvernacular',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprojectvernacular',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.project'),
        ),
        migrations.AddField(
            model_name='historicalprojectvernacular',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.task'),
        ),
        migrations.AddField(
            model_name='historicalprojectwishlist',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.profile'),
        ),
        migrations.AddField(
            model_name='historicalprojectwishlist',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprojectwishlist',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shikshalokam.project'),
        ),
        migrations.AddField(
            model_name='learningresources',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningresources',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_resource', to='shikshalokam.project'),
        ),
        migrations.AddField(
            model_name='projectvernacular',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectvernacular',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_vernacular', to='shikshalokam.project'),
        ),
        migrations.AddField(
            model_name='projectvernacular',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_vernacular', to='shikshalokam.task'),
        ),
        migrations.AddField(
            model_name='projectwishlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='chatbot.profile'),
        ),
        migrations.AddField(
            model_name='projectwishlist',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='shikshalokam.project'),
        ),
        migrations.AddIndex(
            model_name='learningresources',
            index=models.Index(fields=['name'], name='learning_re_name_1d34fd_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresources',
            index=models.Index(fields=['link'], name='learning_re_link_3ada67_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresources',
            index=models.Index(fields=['created_at'], name='learning_re_created_9ceff0_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresources',
            index=models.Index(fields=['resource_id'], name='learning_re_resourc_dea422_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresources',
            index=models.Index(fields=['project'], name='learning_re_project_ad000b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvernacular',
            index=models.Index(fields=['language'], name='project_ver_languag_c76e83_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvernacular',
            index=models.Index(fields=['created_at'], name='project_ver_created_14765c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvernacular',
            index=models.Index(fields=['project'], name='project_ver_project_43ced1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvernacular',
            index=models.Index(fields=['task'], name='project_ver_task_id_bce298_idx'),
        ),
        migrations.AddIndex(
            model_name='projectwishlist',
            index=models.Index(fields=['author'], name='project_wis_author__01388d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectwishlist',
            index=models.Index(fields=['project'], name='project_wis_project_983af9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectwishlist',
            index=models.Index(fields=['created_at'], name='project_wis_created_6951d7_idx'),
        ),
    ]
