# Generated by Django 5.1.2 on 2025-12-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshalokam', '0004_historicallearningresources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='solution_download_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_download_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
