# Generated by Django 5.1.2 on 2024-10-29 06:00

import chatbot.models.base_models
import chatbot.models.media_models
import chatbot.models.story_models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo_large',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_medium',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_small',
        ),
        migrations.AlterField(
            model_name='companybot',
            name='image',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/uploads'), upload_to=chatbot.models.base_models.CompanyBot.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name='profilemedia',
            name='file',
            field=models.FileField(max_length=1000, storage=django.core.files.storage.FileSystemStorage(location='media/uploads'), upload_to=chatbot.models.media_models.ProfileMedia.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name='storymedia',
            name='file',
            field=models.FileField(max_length=1000, storage=django.core.files.storage.FileSystemStorage(location='media/uploads'), upload_to=chatbot.models.story_models.StoryMedia.get_file_upload_path),
        ),
    ]
