# Generated by Django 5.1.2 on 2024-10-29 10:23

import chatbot.models.media_models
import chatbot.models.story_models
import django_s3_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_company_logo_large_remove_company_logo_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybot',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='image',
        ),
        migrations.AlterField(
            model_name='profilemedia',
            name='file',
            field=models.FileField(max_length=1000, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='static-media.gritworks.ai'), upload_to=chatbot.models.media_models.ProfileMedia.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name='storymedia',
            name='file',
            field=models.FileField(max_length=1000, upload_to=chatbot.models.story_models.StoryMedia.get_file_upload_path),
        ),
    ]
