# Generated by Django 5.1.2 on 2024-11-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_profilemedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileaddress',
            name='country',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
