# Generated by Django 5.1.2 on 2024-12-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_historicalprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='call_duration',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='call_recording_url',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='public_log_url',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='retell_call_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='retell_conversation_eval',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='retell_disconnection_reason',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='twilio_call_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='twilio_call_status',
        ),
    ]
