# Generated by Django 5.1.2 on 2024-12-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_historicalprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_status',
            field=models.CharField(blank=True, choices=[('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('PAUSED', 'PAUSED'), ('RESUME', 'RESUME')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companychat',
            name='status',
            field=models.CharField(blank=True, choices=[('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('PAUSED', 'PAUSED'), ('RESUME', 'RESUME')], max_length=20, null=True),
        ),
    ]
