# Generated by Django 5.1.2 on 2024-12-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_remove_chatsession_call_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='next_session',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='sqs_message_id',
        ),
    ]
