# Generated by Django 5.1.2 on 2024-12-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_chatsession_session_status_and_more'),
        ('chatbot', '0007_remove_chatsession_next_session_and_more'),
    ]

    operations = [
    ]
