# Generated by Django 5.1.2 on 2024-12-12 10:07

import chatbot.models.media_models
import django.db.models.deletion
import django_s3_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_merge_20241206_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('media_type', models.CharField(choices=[('application/pdf', 'PDF'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG')], default='text/plain', max_length=100)),
                ('file', models.FileField(max_length=1000, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='mohini-static.shikshalokam.org'), upload_to=chatbot.models.media_models.Media.get_file_upload_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.companybot')),
            ],
        ),
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=10000)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_values', to='chatbot.media')),
            ],
        ),
        migrations.CreateModel(
            name='MediaVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_vector', to='chatbot.media')),
            ],
        ),
    ]
