# Generated by Django 5.1.2 on 2025-02-07 08:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_media_keyvalue_mediavector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('application/pdf', 'PDF'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/svg+xml', 'SVG')], default='text/plain', max_length=100),
        ),
        migrations.AlterField(
            model_name='storymedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('application/pdf', 'PDF'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/svg+xml', 'SVG')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalBotVernacular',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('language', models.CharField(help_text='Language code, Example for English use en.', max_length=250)),
                ('introductory_message', models.TextField(blank=True, help_text='Provide an introductory message that the bot will present when the conversation starts.', null=True)),
                ('name', models.CharField(blank=True, help_text='Enter the name of the bot.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_bot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bot vernacular',
                'verbose_name_plural': 'historical bot vernaculars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BotVernacular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='Language code, Example for English use en.', max_length=250)),
                ('introductory_message', models.TextField(blank=True, help_text='Provide an introductory message that the bot will present when the conversation starts.', null=True)),
                ('name', models.CharField(blank=True, help_text='Enter the name of the bot.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_vernacular', to='chatbot.companybot')),
            ],
            options={
                'db_table': 'shikshalokam"."bot_vernacular',
                'indexes': [models.Index(fields=['language'], name='bot_vernacu_languag_52e6c8_idx'), models.Index(fields=['created_at'], name='bot_vernacu_created_d1c395_idx'), models.Index(fields=['company_bot'], name='bot_vernacu_company_483975_idx')],
                # 'unique_together': {('company_bot', 'language')},
            },
        ),
    ]
