# Generated by Django 5.1.2 on 2025-02-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_media_media_type_alter_storymedia_media_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybot',
            name='abrupt_introductory_message',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='agent_provider',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='retell_agent_id',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='twilio_queue',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='abrupt_introductory_message',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='agent_provider',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='retell_agent_id',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='twilio_queue',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='language',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='provider_code',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='sample_link',
        ),
        migrations.AddField(
            model_name='voice',
            name='company_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.companybot'),
        ),
        migrations.AddField(
            model_name='voice',
            name='type',
            field=models.CharField(blank=True, choices=[('SpeechToText', 'Speech To Text'), ('TextToText', 'Text To Text'), ('TextToSpeech', 'Text To Speech')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat')], default='AI4Bharat', max_length=300, null=True),
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['company_bot'], name='chatbot_voi_company_9292a4_idx'),
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['created_at'], name='chatbot_voi_created_d21d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['type'], name='chatbot_voi_type_98349d_idx'),
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['provider'], name='chatbot_voi_provide_b4b230_idx'),
        ),
    ]
