# Generated by Django 5.1.2 on 2025-02-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_remove_companybot_abrupt_introductory_message_and_more'),
    ]

    operations = [
    ]
