# Generated by Django 5.1.2 on 2025-02-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_companybot_tool_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='validation_logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
