# Generated by Django 5.1.2 on 2025-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_companybot_tool_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('bedrock/converse',
                                   'BEDROCK_CONVERSE'), ('openai', 'OPENAI')], default='openai', max_length=100),
        ),
        migrations.AddField(
            model_name='companybot',
            name='provider_keys',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('bedrock/converse',
                                   'BEDROCK_CONVERSE'), ('openai', 'OPENAI')], default='openai', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='provider_keys',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
