# Generated by Django 5.1.2 on 2025-02-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_companybot_provider_companybot_provider_keys_and_more'),
        ('chatbot', '0016_story_validation_logs'),
    ]

    operations = [
    ]
