# Generated by Django 5.1.2 on 2025-02-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_story_blurb'),
        ('chatbot', '0017_merge_20250214_1505'),
    ]

    operations = [
    ]
