# Generated by Django 5.1.2 on 2025-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_merge_0012_story_blurb_0017_merge_20250214_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
