# Generated by Django 5.1.2 on 2025-02-20 10:55

import chatbot.models.media_models
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_story_blurb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybot',
            name='max_token',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='companybot',
            name='provider_keys',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='max_token',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='historicalcompanybot',
            name='provider_keys',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='project_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='userid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P1', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storymedia',
            name='source_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='provider_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='sample_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='bot_temperature',
            field=models.FloatField(default=0, help_text='Set the temperature for controlling response randomness (0-1). Lower values produce more deterministic responses.'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='company',
            field=models.ForeignKey(help_text='Select the company this bot belongs to.', on_delete=django.db.models.deletion.CASCADE, to='chatbot.company'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='context',
            field=models.TextField(help_text="Provide the bot's main prompt or description of its purpose."),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='dynamic_context',
            field=models.TextField(blank=True, help_text="Provide dynamic context that can be adjusted during the bot's interactions, such as personalized data.", null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='end_context',
            field=models.TextField(blank=True, help_text='Provide additional prompt or context to append at the end of the main prompt to guide the conversation', null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='filter_score',
            field=models.FloatField(default=0.8, help_text='Set the filter score for bot response selection (0-1). Responses below this score will be filtered out.'),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='introductory_message',
            field=models.CharField(blank=True, help_text='Provide an introductory message that the bot will present when the conversation starts.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct')], default='gpt-4o-mini', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='name',
            field=models.CharField(help_text='Enter the name of the bot.', max_length=100),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='pre_context',
            field=models.TextField(blank=True, help_text='Provide pre-context that will be set before the main prompt to shape the conversation.', null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='route',
            field=models.CharField(default='/', help_text='Specify the route or API endpoint for interacting with the bot.', max_length=100),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='tag_context',
            field=models.TextField(blank=True, help_text='Provide any information or context related to variables (like Python-bound variables) that will be inserted into the prompt.', null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='top_k',
            field=models.IntegerField(default=2, help_text="Set the top-k value for the bot's response selection. This defines how many top options to consider for each response.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='companychat',
            name='source',
            field=models.CharField(choices=[('WEB', 'WEB'), ('PHONE', 'PHONE')], default='WEB', max_length=20),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='bot_question',
            field=models.TextField(blank=True, help_text='Provide the first question that the bot will ask when the state is triggered.', null=True),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='completion_criteria',
            field=models.TextField(blank=True, help_text='Define the criteria required to move from this state to the next state.', null=True),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='context',
            field=models.TextField(blank=True, help_text='Provide the main prompt or description of the state, explaining its purpose.', null=True),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='name',
            field=models.CharField(help_text='Enter the name of the state.', max_length=100),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='step',
            field=models.IntegerField(help_text='Integer representing the order in which state function calling happens. Lower values are called first.'),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='type',
            field=models.CharField(choices=[('MANDATORY', 'MANDATORY'), ('OPTIONAL', 'OPTIONAL')], default='MANDATORY', help_text='Specify whether the state is mandatory or optional.', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='bot_temperature',
            field=models.FloatField(default=0, help_text='Set the temperature for controlling response randomness (0-1). Lower values produce more deterministic responses.'),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select the company this bot belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.company'),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='context',
            field=models.TextField(help_text="Provide the bot's main prompt or description of its purpose."),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='dynamic_context',
            field=models.TextField(blank=True, help_text="Provide dynamic context that can be adjusted during the bot's interactions, such as personalized data.", null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='end_context',
            field=models.TextField(blank=True, help_text='Provide additional prompt or context to append at the end of the main prompt to guide the conversation', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='filter_score',
            field=models.FloatField(default=0.8, help_text='Set the filter score for bot response selection (0-1). Responses below this score will be filtered out.'),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='introductory_message',
            field=models.CharField(blank=True, help_text='Provide an introductory message that the bot will present when the conversation starts.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct')], default='gpt-4o-mini', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='name',
            field=models.CharField(help_text='Enter the name of the bot.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='pre_context',
            field=models.TextField(blank=True, help_text='Provide pre-context that will be set before the main prompt to shape the conversation.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='route',
            field=models.CharField(default='/', help_text='Specify the route or API endpoint for interacting with the bot.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='tag_context',
            field=models.TextField(blank=True, help_text='Provide any information or context related to variables (like Python-bound variables) that will be inserted into the prompt.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='top_k',
            field=models.IntegerField(default=2, help_text="Set the top-k value for the bot's response selection. This defines how many top options to consider for each response.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(max_length=1000, upload_to=chatbot.models.media_models.Media.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalCompanyStateMachine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the state.', max_length=100)),
                ('step', models.IntegerField(help_text='Integer representing the order in which state function calling happens. Lower values are called first.')),
                ('type', models.CharField(choices=[('MANDATORY', 'MANDATORY'), ('OPTIONAL', 'OPTIONAL')], default='MANDATORY', help_text='Specify whether the state is mandatory or optional.', max_length=10)),
                ('bot_question', models.TextField(blank=True, help_text='Provide the first question that the bot will ask when the state is triggered.', null=True)),
                ('completion_criteria', models.TextField(blank=True, help_text='Define the criteria required to move from this state to the next state.', null=True)),
                ('context', models.TextField(blank=True, help_text='Provide the main prompt or description of the state, explaining its purpose.', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_bot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical company state machine',
                'verbose_name_plural': 'historical company state machines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
