# Generated by Django 5.1.2 on 2025-02-20 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_remove_companybot_max_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='max_token',
            field=models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='max_token',
            field=models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
