# Generated by Django 5.1.2 on 2025-02-21 03:29

import chatbot.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_companybot_max_token_historicalcompanybot_max_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='botvernacular',
            name='alt_introductory_message',
            field=models.TextField(blank=True, help_text='Provide an alternate introductory message that the bot will present when the conversation starts.', null=True),
        ),
        migrations.AddField(
            model_name='botvernacular',
            name='error_message',
            field=models.TextField(blank=True, help_text='Provide an error message that the bot will display.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=chatbot.models.base_models.Company.get_file_upload_path),
        ),
        migrations.AddField(
            model_name='historicalbotvernacular',
            name='alt_introductory_message',
            field=models.TextField(blank=True, help_text='Provide an alternate introductory message that the bot will present when the conversation starts.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbotvernacular',
            name='error_message',
            field=models.TextField(blank=True, help_text='Provide an error message that the bot will display.', null=True),
        ),
    ]
