# Generated by Django 5.1.2 on 2025-02-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_botvernacular_alt_introductory_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('bedrock/converse', 'BEDROCK_CONVERSE'), ('openai', 'OPENAI')], default='bedrock/converse', help_text='Select the LLM provider (BEDROCK, BEDROCK_CONVERSE, or OPENAI)', max_length=100),
        ),
        migrations.AddField(
            model_name='companybot',
            name='provider_keys',
            field=models.TextField(blank=True, default='', help_text='API keys or credentials for the selected LLM provider.', max_length=1000),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('bedrock/converse', 'BEDROCK_CONVERSE'), ('openai', 'OPENAI')], default='bedrock/converse', help_text='Select the LLM provider (BEDROCK, BEDROCK_CONVERSE, or OPENAI)', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='provider_keys',
            field=models.TextField(blank=True, default='', help_text='API keys or credentials for the selected LLM provider.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('application/pdf', 'PDF'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/svg+xml', 'SVG'), ('image/webp', 'WEBP')], default='text/plain', max_length=100),
        ),
        migrations.AlterField(
            model_name='storymedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('application/pdf', 'PDF'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/svg+xml', 'SVG'), ('image/webp', 'WEBP')], max_length=100, null=True),
        ),
    ]
