# Generated by Django 5.1.2 on 2025-03-04 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0023_companybot_provider_companybot_provider_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100),
        ),
        migrations.AddField(
            model_name='voice',
            name='voice_speed',
            field=models.FloatField(blank=True, default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('GOOGLE_V1', 'GOOGLE v1 STT'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper')], default='AI4Bharat', max_length=300, null=True),
        ),
    ]
