# Generated by Django 5.1.2 on 2025-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_voice_gender_voice_voice_speed_alter_voice_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('normal', 'guidedReflection'), ('oneshot', 'oneStepReflection')], max_length=100, null=True),
        ),
    ]
