# Generated by Django 5.1.2 on 2025-03-19 09:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0025_chatsession_session_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStoryVernacular',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('translation_json', models.JSONField(blank=True, help_text='JSON object containing translated text in the specified language.', null=True)),
                ('language', models.CharField(help_text='Language code, Example for English use en.', max_length=250)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_bot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical story vernacular',
                'verbose_name_plural': 'historical story vernaculars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StoryVernacular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_json', models.JSONField(blank=True, help_text='JSON object containing translated text in the specified language.', null=True)),
                ('language', models.CharField(help_text='Language code, Example for English use en.', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_vernacular', to='chatbot.companybot')),
            ],
            options={
                'indexes': [models.Index(fields=['language'], name='chatbot_sto_languag_93248d_idx'), models.Index(fields=['created_at'], name='chatbot_sto_created_5678f2_idx'), models.Index(fields=['company_bot'], name='chatbot_sto_company_ac3b1a_idx')],
                'unique_together': {('company_bot', 'language')},
            },
        ),
    ]
