# Generated by Django 5.1.2 on 2025-03-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0027_alter_media_media_type_alter_storymedia_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('template_content', models.TextField(null=True)),
                ('template_type', models.CharField(choices=[('EJS', 'EJS'), ('RAW-TEXT', 'RAW-TEXT')], max_length=100, null=True)),
                ('pdf_strategy', models.CharField(choices=[('HTMLPDF', 'HTMLPDF'), ('PUPPETEER', 'PUPPETEER'), ('HTMLDOCX', 'HTMLDOCX'), ('XLSX', 'XLSX')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
