# Generated by Django 5.1.2 on 2025-03-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0028_mediatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='connect_timeout',
            field=models.FloatField(default=5.0, help_text='Timeout in seconds for establishing a LLM connection.'),
        ),
        migrations.AddField(
            model_name='companybot',
            name='read_timeout',
            field=models.FloatField(default=10.0, help_text='Timeout in seconds for reading a LLM response.'),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='connect_timeout',
            field=models.FloatField(default=5.0, help_text='Timeout in seconds for establishing a LLM connection.'),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='read_timeout',
            field=models.FloatField(default=10.0, help_text='Timeout in seconds for reading a LLM response.'),
        ),
    ]
