# Generated by Django 5.1.2 on 2025-03-31 14:34

import chatbot.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0029_companybot_connect_timeout_companybot_read_timeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companychat',
            name='audio_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=chatbot.models.base_models.CompanyChat.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('normal', 'guidedReflection'), ('oneshot', 'oneStepReflection'), ('shikshalokam_chaupal', 'shikshaChaupal')], max_length=100, null=True),
        ),
    ]
