# Generated by Django 5.1.2 on 2025-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0030_companychat_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('normal', 'guidedReflection'), ('oneshot', 'oneStepReflection'), ('shikshalokam_chaupal', 'shikshaChaupal'), ('reflection', 'reflection'), ('creation', 'creation')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='email',
            field=models.EmailField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=1000),
        ),
    ]
