# Generated by Django 5.1.2 on 2025-04-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0031_alter_chatsession_session_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
