# Generated by Django 5.1.2 on 2025-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0032_alter_historicalprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('login', 'login'), ('reflection', 'reflection')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('login', 'login'), ('reflection', 'reflection')], max_length=500, null=True),
        ),
    ]
