# Generated by Django 5.1.2 on 2025-04-12 09:56

import chatbot.models.story_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0033_historicalprofile_latest_flow_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymedia',
            name='file_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='storymedia',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=chatbot.models.story_models.StoryMedia.get_file_upload_path),
        ),
    ]
