# Generated by Django 5.1.2 on 2025-05-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0034_storymedia_file_url_alter_storymedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='companychat',
            name='file_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
