# Generated by Django 5.1.2 on 2025-05-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0035_companychat_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='other_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('GOOGLE_V1', 'GOOGLE v1 STT'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam')], default='AI4Bharat', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='type',
            field=models.CharField(blank=True, choices=[('SpeechToText', 'Speech To Text'), ('TextToText', 'Text To Text'), ('TextToSpeech', 'Text To Speech'), ('Transliterate', 'Transliteration')], max_length=300, null=True),
        ),
    ]
