# Generated by Django 5.1.2 on 2025-06-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0037_alter_companybot_llm_model_alter_companychat_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatemachine',
            name='use_stage_chats',
            field=models.BooleanField(default=False, help_text='If True, only chats from this stage will be included and passed to the LLM.', verbose_name='Use Stage Chats'),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='use_stage_chats',
            field=models.BooleanField(default=False, help_text='If True, only chats from this stage will be included and passed to the LLM.', verbose_name='Use Stage Chats'),
        ),
    ]
