# Generated by Django 5.1.2 on 2025-07-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0038_companystatemachine_use_stage_chats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companychat',
            name='other_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('normal', 'Guided Reflection'), ('oneshot', 'One Step Reflection'), ('shikshalokam_chaupal', 'Shiksha Chaupal'), ('reflection', 'Reflection'), ('creation', 'Creation'), ('megaPTM', 'Mega PTM')], max_length=100, null=True),
        ),
    ]
