# Generated by Django 5.1.2 on 2025-07-11 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0039_companychat_other_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatemachine',
            name='output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip Stage If Needed'), ('ENRICH', 'Use Output in Prompt'), ('CUSTOM', 'Custom Logic')], default='NONE', help_text="Define how to use the preprocess output: 'Skip' means use output to decide if stage should be skipped; 'Enrich' means use output in this stage's prompt; 'Custom' means run custom logic on the output.", max_length=10),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='preprocess_bot',
            field=models.ForeignKey(blank=True, help_text='Select which Bot to use for preprocessing for complex logic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preprocess_bots', to='chatbot.companybot'),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='preprocess_prompt',
            field=models.TextField(blank=True, help_text='Define the skip logic prompt if Preprocess Type is SIMPLE. ', null=True),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='preprocess_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SIMPLE', 'Simple Prompt'), ('COMPLEX', 'Use Preprocess Bot')], default='NONE', help_text="Choose how this stage should be preprocessed: 'Simple Prompt' lets you define a direct prompt, 'Use Preprocess Bot' lets you select a separate bot to handle complex logic.", max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip Stage If Needed'), ('ENRICH', 'Use Output in Prompt'), ('CUSTOM', 'Custom Logic')], default='NONE', help_text="Define how to use the preprocess output: 'Skip' means use output to decide if stage should be skipped; 'Enrich' means use output in this stage's prompt; 'Custom' means run custom logic on the output.", max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='preprocess_bot',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select which Bot to use for preprocessing for complex logic.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot'),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='preprocess_prompt',
            field=models.TextField(blank=True, help_text='Define the skip logic prompt if Preprocess Type is SIMPLE. ', null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='preprocess_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SIMPLE', 'Simple Prompt'), ('COMPLEX', 'Use Preprocess Bot')], default='NONE', help_text="Choose how this stage should be preprocessed: 'Simple Prompt' lets you define a direct prompt, 'Use Preprocess Bot' lets you select a separate bot to handle complex logic.", max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('login', 'login'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('login', 'login'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM')], max_length=500, null=True),
        ),
    ]
