# Generated by Django 5.1.2 on 2025-07-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0040_companystatemachine_output_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companystatemachine',
            old_name='output_mode',
            new_name='preprocess_output_mode',
        ),
        migrations.RenameField(
            model_name='historicalcompanystatemachine',
            old_name='output_mode',
            new_name='preprocess_output_mode',
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='postprocess_bot',
            field=models.ForeignKey(blank=True, help_text='Select which Bot to use for postprocessing for complex logic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postprocess_bots', to='chatbot.companybot'),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='postprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip Stage If Needed')], default='NONE', help_text='Define how to use the postprocess output.', max_length=10),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='postprocess_prompt',
            field=models.TextField(blank=True, help_text='Define the postprocess prompt if Postprocess Type is SIMPLE.', null=True),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='postprocess_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SIMPLE', 'Simple Prompt'), ('COMPLEX', 'Use Postprocess Bot')], default='NONE', help_text="Choose how this stage should be postprocessed: 'Simple Prompt' lets you define a direct prompt, 'Use Postprocess Bot' lets you select a separate bot to handle complex logic.", max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='postprocess_bot',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select which Bot to use for postprocessing for complex logic.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot'),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='postprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip Stage If Needed')], default='NONE', help_text='Define how to use the postprocess output.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='postprocess_prompt',
            field=models.TextField(blank=True, help_text='Define the postprocess prompt if Postprocess Type is SIMPLE.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='postprocess_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SIMPLE', 'Simple Prompt'), ('COMPLEX', 'Use Postprocess Bot')], default='NONE', help_text="Choose how this stage should be postprocessed: 'Simple Prompt' lets you define a direct prompt, 'Use Postprocess Bot' lets you select a separate bot to handle complex logic.", max_length=10),
        ),
    ]
