# Generated by Django 5.1.2 on 2025-07-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0041_rename_output_mode_companystatemachine_preprocess_output_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='other_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='postprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip Next Stage')], default='NONE', help_text='Define how to use the postprocess output.', max_length=10),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='preprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip This Stage'), ('ENRICH', 'Add Output to Prompt'), ('CUSTOM', 'Run Custom Logic')], default='NONE', help_text="Define how to use the preprocess output: 'Skip' means use output to decide if stage should be skipped; 'Enrich' means use output in this stage's prompt; 'Custom' means run custom logic on the output.", max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='postprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip Next Stage')], default='NONE', help_text='Define how to use the postprocess output.', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='preprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip This Stage'), ('ENRICH', 'Add Output to Prompt'), ('CUSTOM', 'Run Custom Logic')], default='NONE', help_text="Define how to use the preprocess output: 'Skip' means use output to decide if stage should be skipped; 'Enrich' means use output in this stage's prompt; 'Custom' means run custom logic on the output.", max_length=10),
        ),
    ]
