# Generated by Django 5.1.2 on 2025-08-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0042_chatsession_other_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('login', 'login'), ('sso', 'sso'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('login', 'login'), ('sso', 'sso'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM')], max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='StoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu')], max_length=10)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True, null=True)),
                ('blurb', models.TextField(blank=True, null=True)),
                ('tweet', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('action_steps', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('micro_improvement', models.TextField(blank=True, null=True)),
                ('translated_other_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chatbot.story')),
            ],
            options={
                'indexes': [models.Index(fields=['story', 'language'], name='chatbot_sto_story_i_fd02b4_idx')],
                'unique_together': {('story', 'language')},
            },
        ),
    ]
