# Generated by Django 5.1.2 on 2025-08-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0043_alter_historicalprofile_latest_flow_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytranslation',
            name='formatted_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
