# Generated by Django 5.1.2 on 2025-08-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0044_storytranslation_formatted_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storytranslation',
            old_name='translated_other_params',
            new_name='other_params',
        ),
    ]
