# Generated by Django 5.1.2 on 2025-08-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0046_chatsession_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatemachine',
            name='skip_to_step',
            field=models.IntegerField(blank=True, help_text='If set, the flow will skip directly to this step number when skip conditions are met.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='skip_to_step',
            field=models.IntegerField(blank=True, help_text='If set, the flow will skip directly to this step number when skip conditions are met.', null=True),
        ),
    ]
