# Generated by Django 5.1.2 on 2025-08-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0048_historicaltheme_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltheme',
            name='master_theme',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If using a master theme, select the theme to inherit from.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.theme'),
        ),
        migrations.AddField(
            model_name='historicaltheme',
            name='theme_type',
            field=models.CharField(choices=[('custom', 'Custom for Bot'), ('master', 'Using Master Theme')], default='custom', help_text='Indicates if this theme is custom or uses a master theme.', max_length=10),
        ),
        migrations.AddField(
            model_name='theme',
            name='master_theme',
            field=models.ForeignKey(blank=True, help_text='If using a master theme, select the theme to inherit from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_themes', to='chatbot.theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_type',
            field=models.CharField(choices=[('custom', 'Custom for Bot'), ('master', 'Using Master Theme')], default='custom', help_text='Indicates if this theme is custom or uses a master theme.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['theme_type'], name='chatbot_the_theme_t_f3c34f_idx'),
        ),
    ]
