# Generated by Django 5.1.2 on 2025-08-20 10:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0049_historicaltheme_master_theme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Global Tag', 'verbose_name_plural': 'Global Tags'},
        ),
        migrations.AddField(
            model_name='media',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(related_name='medias', to='chatbot.tag'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('application/pdf', 'PDF'), ('application/msword', 'DOC'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'DOCX'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('application/vnd.ms-excel', 'XLS'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'XLSX')], default='text/plain', max_length=100),
        ),
        migrations.AddIndex(
            model_name='media',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('extracted_text', config='english'), name='media_extracted_text_gin'),
        ),
    ]
