# Generated by Django 5.1.2 on 2025-08-21 01:14

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0050_alter_tag_options_media_extracted_text_media_tags_and_more'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='media',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extracted_text'], name='media_extracted_text_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
