# Generated by Django 5.1.2 on 2025-08-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0051_media_media_extracted_text_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='source_type',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AI_EXTRACTED', 'AI Extracted from Document'), ('AI_GENERATED', 'AI Generated')], max_length=50, null=True),
        ),
    ]
