# Generated by Django 5.1.2 on 2025-08-29 07:37

import chatbot.models.media_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0052_tag_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='source_type',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AI_EXTRACTED', 'AI Extracted'), ('AI_GENERATED', 'AI Generated')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to=chatbot.models.media_models.MediaImage.get_file_upload_path)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('index', models.IntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('application/pdf', 'PDF'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/svg+xml', 'SVG'), ('image/webp', 'WEBP'), ('image/heif', 'HEIF'), ('image/heic', 'HEIC')], max_length=100, null=True)),
                ('base64_str', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chatbot.media')),
            ],
            options={
                'ordering': ['page', 'index'],
            },
        ),
    ]
