# Generated by Django 5.1.2 on 2025-09-01 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0054_tag_description_alter_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdocuments', to='chatbot.media'),
        ),
    ]
