# Generated by Django 5.1.2 on 2025-09-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0055_media_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='other_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='other_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('application/pdf', 'PDF'), ('application/msword', 'DOC'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'DOCX'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('application/vnd.ms-excel', 'XLS'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'XLSX')], default='text/plain', max_length=100),
        ),
    ]
