# Generated by Django 5.1.2 on 2025-09-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0057_historicalmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
