# Generated by Django 5.1.2 on 2025-09-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0058_alter_keyvalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
