# Generated by Django 5.1.2 on 2025-09-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0059_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedia',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.company'),
        ),
        migrations.AddField(
            model_name='media',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.company'),
        ),
    ]
