# Generated by Django 5.1.2 on 2025-09-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0060_historicalmedia_organization_media_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatemachine',
            name='text_conversion_type',
            field=models.CharField(choices=[('TRANSLATE', 'Translation'), ('TRANSLITERATE', 'Transliteration')], default='TRANSLATE', help_text="Choose how to process this field's text: 'Translation' converts meaning into another language, 'Transliteration' preserves sound using another script.", max_length=15),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='text_conversion_type',
            field=models.CharField(choices=[('TRANSLATE', 'Translation'), ('TRANSLITERATE', 'Transliteration')], default='TRANSLATE', help_text="Choose how to process this field's text: 'Translation' converts meaning into another language, 'Transliteration' preserves sound using another script.", max_length=15),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('normal', 'Guided Reflection'), ('oneshot', 'One Step Reflection'), ('shikshalokam_chaupal', 'Shiksha Chaupal'), ('reflection', 'Reflection'), ('creation', 'Creation'), ('megaPTM', 'Mega PTM'), ('listening-activity', 'Listening Activity')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('listening-activity', 'Listening Activity'), ('login', 'login'), ('sso', 'sso'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('listening-activity', 'Listening Activity'), ('login', 'login'), ('sso', 'sso'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM')], max_length=500, null=True),
        ),
    ]
