# Generated by Django 5.1.2 on 2025-09-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0061_companystatemachine_text_conversion_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatemachine',
            name='tool_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='tool_context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
