# Generated by Django 5.1.2 on 2025-10-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0062_companystatemachine_tool_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedia',
            name='display_mode',
            field=models.CharField(choices=[('visible', 'Visible to All'), ('ai_only', 'AI Only (Hidden from UI)'), ('private', 'Private (Hidden from UI and AI)')], default='visible', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='display_mode',
            field=models.CharField(choices=[('visible', 'Visible to All'), ('ai_only', 'AI Only (Hidden from UI)'), ('private', 'Private (Hidden from UI and AI)')], default='visible', max_length=20),
        ),
    ]
