# Generated by Django 5.1.2 on 2025-10-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0064_storytranslation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='block',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='district',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='storytranslation',
            name='block',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='storytranslation',
            name='district',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='storytranslation',
            name='state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
