# Generated by Django 5.1.2 on 2025-10-31 09:01

import chatbot.models.media_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0065_story_block_story_district_story_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedia',
            name='markdown_file',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='markdown_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=chatbot.models.media_models.Media.get_file_upload_path),
        ),
    ]
