# Generated by Django 5.1.2 on 2025-11-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0065_story_block_story_district_story_state_and_more'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='botvernacular',
        #     unique_together=set(),
        # ),
        migrations.AlterUniqueTogether(
            name='storyvernacular',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='botvernacular',
            name='company_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_vernacular', to='chatbot.companybot'),
        ),
        migrations.AlterField(
            model_name='storyvernacular',
            name='company_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_vernacular', to='chatbot.companybot'),
        ),
    ]
