# Generated by Django 5.1.2 on 2025-11-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0066_alter_botvernacular_unique_together_and_more'),
        ('chatbot', '0066_historicalmedia_markdown_file_media_markdown_file'),
    ]

    operations = [
    ]
