# Generated by Django 5.1.2 on 2025-12-13 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0067_merge_20251116_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='chat_history_limit',
            field=models.IntegerField(default=1000, help_text='Controls how many of the most recent chat messages are included as conversation history when making an LLM request.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='chat_history_limit',
            field=models.IntegerField(default=1000, help_text='Controls how many of the most recent chat messages are included as conversation history when making an LLM request.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('normal', 'Guided Reflection'), ('oneshot', 'One Step Reflection'), ('shikshalokam_chaupal', 'Shiksha Chaupal'), ('reflection', 'Reflection'), ('creation', 'Creation'), ('megaPTM', 'Mega PTM'), ('YLC', 'YLC'), ('listening-activity', 'Listening Activity'), ('parent_perception_survey', 'Parent Perception Survey')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('listening-activity', 'Listening Activity'), ('login', 'login'), ('sso', 'sso'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM'), ('YLC', 'YLC'), ('parent_perception_survey', 'Parent Perception Survey'), ('creation', 'Creation')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('listening-activity', 'Listening Activity'), ('login', 'login'), ('sso', 'sso'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM'), ('YLC', 'YLC'), ('parent_perception_survey', 'Parent Perception Survey'), ('creation', 'Creation')], max_length=500, null=True),
        ),
    ]
