# Generated by Django 5.1.2 on 2025-11-29 06:14

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0067_merge_20251116_1325'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='strategy',
            field=models.CharField(blank=True, choices=[('oneshot', 'One Shot'), ('guided_guest', 'Guided Guest'), ('guest_discussion', 'Guest Discussion'), ('common', 'Common')], help_text='Select the strategy or approach this bot uses for conversations.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='operation_type',
            field=models.CharField(choices=[('llm', 'LLM'), ('non_llm', 'Non-LLM')], default='llm', help_text='Choose whether this state uses LLM or non-LLM processing.', max_length=20),
        ),
        migrations.AddField(
            model_name='companystatemachine',
            name='skip_if_authenticated',
            field=models.BooleanField(default=False, help_text='If True, this state will be skipped for authenticated users.'),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='strategy',
            field=models.CharField(blank=True, choices=[('oneshot', 'One Shot'), ('guided_guest', 'Guided Guest'), ('guest_discussion', 'Guest Discussion'), ('common', 'Common')], help_text='Select the strategy or approach this bot uses for conversations.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='operation_type',
            field=models.CharField(choices=[('llm', 'LLM'), ('non_llm', 'Non-LLM')], default='llm', help_text='Choose whether this state uses LLM or non-LLM processing.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcompanystatemachine',
            name='skip_if_authenticated',
            field=models.BooleanField(default=False, help_text='If True, this state will be skipped for authenticated users.'),
        ),
        migrations.CreateModel(
            name='HistoricalI18nTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, help_text="Unique tag name for grouping translations (e.g., 'welcome_message', 'button_labels').", max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical I18n Tag',
                'verbose_name_plural': 'historical I18n Tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPDFTemplates',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('template', models.TextField(help_text='Template content for PDF generation (e.g., HTML, EJS template).')),
                ('template_name', models.CharField(db_index=True, help_text='Unique name identifier for this template.', max_length=255)),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('auth', 'Authenticated'), ('all', 'All')], default='all', help_text='User types that can use this template (guest, auth, or all).', max_length=20)),
                ('constants_json', models.JSONField(blank=True, help_text='JSON object containing constants/variables used in the template.', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical PDF Template',
                'verbose_name_plural': 'historical PDF Templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='I18nTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text="Unique tag name for grouping translations (e.g., 'welcome_message', 'button_labels').", max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'I18n Tag',
                'verbose_name_plural': 'I18n Tags',
                'ordering': ['tag_name'],
                'indexes': [models.Index(fields=['tag_name'], name='chatbot_i18_tag_nam_80094f_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalI18nTranslation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('variable_name', models.CharField(help_text="Variable name for this translation (e.g., 'title', 'description', 'button_text').", max_length=255)),
                ('language', models.CharField(help_text="Language code (e.g., 'en', 'hi', 'kn', 'te').", max_length=10)),
                ('value', models.TextField(help_text='Translated text value for this variable in the specified language.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tag_id', models.ForeignKey(blank=True, db_constraint=False, help_text='The tag this translation belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.i18ntag')),
            ],
            options={
                'verbose_name': 'historical I18n Translation',
                'verbose_name_plural': 'historical I18n Translations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this image configuration.', max_length=100)),
                ('max_images', models.IntegerField(default=1, help_text='Maximum number of images allowed.', validators=[django.core.validators.MinValueValidator(0)])),
                ('image_size', models.IntegerField(default=5242880, help_text='Maximum image size in bytes (default: 5MB).', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Configuration',
                'verbose_name_plural': 'Image Configurations',
                'indexes': [models.Index(fields=['name'], name='chatbot_ima_name_1525db_idx')],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.CharField(help_text='Name of the flow.', max_length=255)),
                ('flow_route', models.CharField(help_text='Route/path for accessing this flow.', max_length=255)),
                ('languages', models.JSONField(default=list, help_text="List of supported language codes (e.g., ['en', 'hi', 'kn']).")),
                ('hidden', models.BooleanField(default=False, help_text='If True, this flow will be hidden from public listing.')),
                ('active', models.BooleanField(default=True, help_text='If False, this flow will be disabled and not accessible.')),
                ('websocket_url', models.URLField(blank=True, help_text='WebSocket URL for real-time communication (optional).', max_length=500, null=True)),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('auth', 'Authenticated'), ('all', 'All')], default='all', help_text='User types allowed to access this flow (guest, auth, or all).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_id', models.ForeignKey(help_text='The main bot associated with this flow.', on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='chatbot.companybot')),
                ('parent_flow_id', models.ForeignKey(blank=True, help_text='Parent flow if this is a sub-flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_flows', to='chatbot.flow')),
                ('story_bot_id', models.ForeignKey(blank=True, help_text='Optional secondary bot for story-related functionality.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_flows', to='chatbot.companybot')),
                ('image_config_id', models.ForeignKey(blank=True, help_text='Image configuration settings for this flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='chatbot.imageconfiguration')),
            ],
            options={
                'verbose_name': 'Flow',
                'verbose_name_plural': 'Flows',
            },
        ),
        migrations.CreateModel(
            name='PDFTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(help_text='Template content for PDF generation (e.g., HTML, EJS template).')),
                ('template_name', models.CharField(help_text='Unique name identifier for this template.', max_length=255, unique=True)),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('auth', 'Authenticated'), ('all', 'All')], default='all', help_text='User types that can use this template (guest, auth, or all).', max_length=20)),
                ('constants_json', models.JSONField(blank=True, help_text='JSON object containing constants/variables used in the template.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF Template',
                'verbose_name_plural': 'PDF Templates',
                'indexes': [models.Index(fields=['template_name'], name='chatbot_pdf_templat_b240ab_idx'), models.Index(fields=['user_type'], name='chatbot_pdf_user_ty_3368e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFlow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('flow_name', models.CharField(help_text='Name of the flow.', max_length=255)),
                ('flow_route', models.CharField(help_text='Route/path for accessing this flow.', max_length=255)),
                ('languages', models.JSONField(default=list, help_text="List of supported language codes (e.g., ['en', 'hi', 'kn']).")),
                ('hidden', models.BooleanField(default=False, help_text='If True, this flow will be hidden from public listing.')),
                ('active', models.BooleanField(default=True, help_text='If False, this flow will be disabled and not accessible.')),
                ('websocket_url', models.URLField(blank=True, help_text='WebSocket URL for real-time communication (optional).', max_length=500, null=True)),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('auth', 'Authenticated'), ('all', 'All')], default='all', help_text='User types allowed to access this flow (guest, auth, or all).', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bot_id', models.ForeignKey(blank=True, db_constraint=False, help_text='The main bot associated with this flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_flow_id', models.ForeignKey(blank=True, db_constraint=False, help_text='Parent flow if this is a sub-flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.flow')),
                ('story_bot_id', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional secondary bot for story-related functionality.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot')),
                ('image_config_id', models.ForeignKey(blank=True, db_constraint=False, help_text='Image configuration settings for this flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.imageconfiguration')),
                ('template_id', models.ForeignKey(blank=True, db_constraint=False, help_text='PDF template for generating documents in this flow.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.pdftemplates')),
            ],
            options={
                'verbose_name': 'historical Flow',
                'verbose_name_plural': 'historical Flows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='flow',
            name='template_id',
            field=models.ForeignKey(blank=True, help_text='PDF template for generating documents in this flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='chatbot.pdftemplates'),
        ),
        migrations.CreateModel(
            name='I18nTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(help_text="Variable name for this translation (e.g., 'title', 'description', 'button_text').", max_length=255)),
                ('language', models.CharField(help_text="Language code (e.g., 'en', 'hi', 'kn', 'te').", max_length=10)),
                ('value', models.TextField(help_text='Translated text value for this variable in the specified language.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_id', models.ForeignKey(help_text='The tag this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chatbot.i18ntag')),
            ],
            options={
                'verbose_name': 'I18n Translation',
                'verbose_name_plural': 'I18n Translations',
                'ordering': ['tag_id', 'variable_name', 'language'],
                'indexes': [models.Index(fields=['tag_id', 'variable_name', 'language'], name='chatbot_i18_tag_id__7eb096_idx'), models.Index(fields=['language'], name='chatbot_i18_languag_e2489a_idx'), models.Index(fields=['variable_name'], name='chatbot_i18_variabl_04d419_idx')],
                'unique_together': {('tag_id', 'variable_name', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['flow_route'], name='chatbot_flo_flow_ro_f6fbff_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['bot_id'], name='chatbot_flo_bot_id__f110e9_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['active'], name='chatbot_flo_active_a1007c_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['hidden'], name='chatbot_flo_hidden_55cd22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('flow_route', 'bot_id')},
        ),
    ]
