# Generated by Django 5.1.2 on 2025-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0068_companybot_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('school-survey', 'school-survey'), ('listening-activity', 'Listening Activity'), ('login', 'login'), ('sso', 'sso'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM'), ('YLC', 'YLC')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('school-survey', 'school-survey'), ('listening-activity', 'Listening Activity'), ('login', 'login'), ('sso', 'sso'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM'), ('YLC', 'YLC')], max_length=500, null=True),
        ),
    ]
