# Generated by Django 5.1.2 on 2025-12-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0068_companybot_chat_history_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedia',
            name='download_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalmedia',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='download_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
