# Generated by Django 5.1.2 on 2025-12-30 05:43

import chatbot.models.media_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0069_historicalmedia_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedia',
            name='thumbnail',
            field=models.TextField(blank=True, help_text='Auto-generated preview thumbnail', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated preview thumbnail', max_length=1000, null=True, upload_to=chatbot.models.media_models.Media.get_thumbnail_upload_path),
        ),
    ]
