# Generated by Django 5.1.2 on 2025-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0069_alter_historicalprofile_latest_flow_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='websocket_url',
            field=models.CharField(blank=True, help_text='WebSocket path for real-time communication (e.g., ws/common). Do not include protocol or host.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalflow',
            name='websocket_url',
            field=models.CharField(blank=True, help_text='WebSocket path for real-time communication (e.g., ws/common). Do not include protocol or host.', max_length=500, null=True),
        ),
    ]
