# Generated by Django 5.1.2 on 2025-12-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0068_companybot_chat_history_limit_and_more'),
        ('chatbot', '0070_alter_flow_websocket_url_and_more'),
    ]

    operations = [
    ]
