# Generated by Django 5.1.2 on 2026-01-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0070_historicalmedia_thumbnail_media_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='stream',
            field=models.BooleanField(default=True, help_text='Enable streaming mode for LLM responses. When enabled, the bot will send response chunks in real-time as they are generated (streaming). When disabled, the bot will wait for the complete response before sending it (non-streaming). Streaming provides better user experience with faster perceived response times, while non-streaming ensures complete responses are received at once.'),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='stream',
            field=models.BooleanField(default=True, help_text='Enable streaming mode for LLM responses. When enabled, the bot will send response chunks in real-time as they are generated (streaming). When disabled, the bot will wait for the complete response before sending it (non-streaming). Streaming provides better user experience with faster perceived response times, while non-streaming ensures complete responses are received at once.'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('normal', 'Guided Reflection'), ('oneshot', 'One Step Reflection'), ('shikshalokam_chaupal', 'Shiksha Chaupal'), ('reflection', 'Reflection'), ('creation', 'Creation'), ('megaPTM', 'Mega PTM'), ('YLC', 'YLC'), ('listening-activity', 'Listening Activity'), ('parent_perception_survey', 'Parent Perception Survey'), ('lcf', 'LCF'), ('lfa', 'LFA'), ('free_flow', 'Free-Flow')], max_length=100, null=True),
        ),
    ]
