# Generated by Django 5.1.2 on 2026-01-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0071_add_stream_field_to_company_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybot',
            name='stream',
            field=models.BooleanField(default=False, help_text='Enable streaming mode for LLM responses.'),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='stream',
            field=models.BooleanField(default=False, help_text='Enable streaming mode for LLM responses.'),
        ),
    ]
