# Generated by Django 5.1.2 on 2025-12-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0071_merge_20251218_1654'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalflow',
            name='template_id',
        ),
        migrations.AddField(
            model_name='historicalpdftemplates',
            name='flow',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Flow associated with this template.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.flow'),
        ),
        migrations.AddField(
            model_name='pdftemplates',
            name='flow',
            field=models.ForeignKey(blank=True, help_text='Flow associated with this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_templates', to='chatbot.flow'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='flow_route',
            field=models.CharField(help_text='Route/path for accessing this flow.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='languages',
            field=models.JSONField(default=['en', 'hi', 'kn', 'te'], help_text="List of supported language codes (e.g., ['en', 'hi', 'kn'])."),
        ),
        migrations.AlterField(
            model_name='flow',
            name='websocket_url',
            field=models.CharField(default='ws/common/', help_text='WebSocket path for real-time communication (e.g., ws/common). Do not include protocol or host.', max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalflow',
            name='flow_route',
            field=models.CharField(db_index=True, help_text='Route/path for accessing this flow.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalflow',
            name='languages',
            field=models.JSONField(default=['en', 'hi', 'kn', 'te'], help_text="List of supported language codes (e.g., ['en', 'hi', 'kn'])."),
        ),
        migrations.AlterField(
            model_name='historicalflow',
            name='websocket_url',
            field=models.CharField(default='ws/common/', help_text='WebSocket path for real-time communication (e.g., ws/common). Do not include protocol or host.', max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('school-survey', 'school-survey'), ('listening-activity', 'Listening Activity'), ('login', 'login'), ('sso', 'sso'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM'), ('YLC', 'YLC'), ('parent_perception_survey', 'Parent Perception Survey'), ('creation', 'Creation')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_flow_used',
            field=models.CharField(blank=True, choices=[('guest-discussion', 'guest-discussion'), ('login-discussion', 'login-discussion'), ('guest-mi-story', 'guest-mi-story'), ('school-survey', 'school-survey'), ('listening-activity', 'Listening Activity'), ('login', 'login'), ('sso', 'sso'), ('reflection', 'reflection'), ('megaPTM', 'Mega PTM'), ('YLC', 'YLC'), ('parent_perception_survey', 'Parent Perception Survey'), ('creation', 'Creation')], max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='flow',
            name='template_id',
        ),
    ]
