# Generated by Django 5.1.2 on 2026-01-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0072_alter_companybot_stream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedia',
            name='external_file_id',
            field=models.CharField(blank=True, help_text='External provider file identifier used for vector indexing (e.g. OpenAI Files API file_id)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='external_file_id',
            field=models.CharField(blank=True, help_text='External provider file identifier used for vector indexing (e.g. OpenAI Files API file_id)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='preprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip This Stage')], default='NONE', help_text="Define how to use the preprocess output: 'Skip' means use output to decide if stage should be skipped; 'Enrich' means use output in this stage's prompt; 'Custom' means run custom logic on the output.", max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='preprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip This Stage')], default='NONE', help_text="Define how to use the preprocess output: 'Skip' means use output to decide if stage should be skipped; 'Enrich' means use output in this stage's prompt; 'Custom' means run custom logic on the output.", max_length=10),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='media_type',
            field=models.CharField(blank=True, choices=[('application/pdf', 'PDF'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/svg+xml', 'SVG'), ('image/webp', 'WEBP'), ('image/heif', 'HEIF'), ('image/heic', 'HEIC'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'XLSX')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storymedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('application/pdf', 'PDF'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/svg+xml', 'SVG'), ('image/webp', 'WEBP'), ('image/heif', 'HEIF'), ('image/heic', 'HEIC'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'XLSX')], max_length=100, null=True),
        ),
    ]
