# Generated by Django 5.1.2 on 2025-12-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0072_alter_flow_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flow',
            name='chatbot_flo_bot_id__f110e9_idx',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='bot_id',
            new_name='bot',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='image_config_id',
            new_name='image_config',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='parent_flow_id',
            new_name='parent_flow',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='story_bot_id',
            new_name='story_bot',
        ),
        migrations.RenameField(
            model_name='historicalflow',
            old_name='bot_id',
            new_name='bot',
        ),
        migrations.RenameField(
            model_name='historicalflow',
            old_name='image_config_id',
            new_name='image_config',
        ),
        migrations.RenameField(
            model_name='historicalflow',
            old_name='parent_flow_id',
            new_name='parent_flow',
        ),
        migrations.RenameField(
            model_name='historicalflow',
            old_name='story_bot_id',
            new_name='story_bot',
        ),
        migrations.AddField(
            model_name='flow',
            name='story_validation_bot',
            field=models.ForeignKey(blank=True, help_text='Optional secondary bot for story-related functionality.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_validation_flows', to='chatbot.companybot'),
        ),
        migrations.AddField(
            model_name='historicalflow',
            name='story_validation_bot',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional secondary bot for story-related functionality.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['bot'], name='chatbot_flo_bot_id_58878f_idx'),
        ),
    ]
