# Generated by Django 5.1.2 on 2025-12-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0073_remove_flow_chatbot_flo_bot_id__f110e9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='create_story',
            field=models.CharField(choices=[('guest', 'Guest'), ('auth', 'Authenticated'), ('all', 'All'), ('none', 'None')], default='all', help_text='Whether to post process the story or not', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalflow',
            name='create_story',
            field=models.CharField(choices=[('guest', 'Guest'), ('auth', 'Authenticated'), ('all', 'All'), ('none', 'None')], default='all', help_text='Whether to post process the story or not', max_length=20),
        ),
    ]
