# Generated by Django 5.1.2 on 2025-12-22 14:36

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0074_flow_create_story_historicalflow_create_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImageConfiguration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this image configuration.', max_length=100)),
                ('max_images', models.IntegerField(default=1, help_text='Maximum number of images allowed.', validators=[django.core.validators.MinValueValidator(0)])),
                ('image_size', models.IntegerField(default=5242880, help_text='Maximum image size in bytes (default: 5MB).', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Image Configuration',
                'verbose_name_plural': 'historical Image Configurations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('SpeechToText', 'Speech To Text'), ('TextToText', 'Text To Text'), ('TextToSpeech', 'Text To Speech'), ('Transliterate', 'Transliteration')], max_length=300, null=True)),
                ('provider', models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('GOOGLE_V1', 'GOOGLE v1 STT'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam')], default='AI4Bharat', max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_link', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_code', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100)),
                ('voice_speed', models.FloatField(blank=True, default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(4.0)])),
                ('other_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_bot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical voice',
                'verbose_name_plural': 'historical voices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
