# Generated by Django 5.1.2 on 2025-12-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0075_historicalimageconfiguration_historicalvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='latest_flow',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.flow'),
        ),
        migrations.AddField(
            model_name='profile',
            name='latest_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.flow'),
        ),
    ]
