# Generated by Django 5.1.2 on 2025-12-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0070_historicalmedia_thumbnail_media_thumbnail'),
        ('chatbot', '0076_historicalprofile_latest_flow_profile_latest_flow'),
    ]

    operations = [
    ]
