# Generated by Django 5.1.2 on 2026-01-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0073_historicalmedia_external_file_id_and_more'),
        ('chatbot', '0077_merge_20260101_0105'),
    ]

    operations = [
    ]
