# Generated by Django 5.2 on 2026-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0078_merge_20260126_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4.1', 'GPT4_1'), ('gpt-4.1-mini', 'GPT4_1-MINI'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct'), ('gpt-5.2', 'GPT_5_2'), ('gpt-5.2-pro', 'GPT_5_2_PRO'), ('gpt-5-mini', 'GPT_5_MINI')], default='gpt-4o-mini', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='postprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip Next Stage')], default='NONE', help_text='Define how to use the postprocess output.', max_length=100),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='postprocess_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SIMPLE', 'Simple Prompt'), ('COMPLEX', 'Use Postprocess Bot')], default='NONE', help_text="Choose how this stage should be postprocessed: 'Simple Prompt' lets you define a direct prompt, 'Use Postprocess Bot' lets you select a separate bot to handle complex logic.", max_length=100),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='preprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip This Stage'), ('MODIFY_QUESTION', 'Modify Bot Question')], default='NONE', help_text="Define how to use the preprocess output: 'Skip' means use output to decide if stage should be skipped; 'Enrich' means use output in this stage's prompt; 'Custom' means run custom logic on the output.", max_length=100),
        ),
        migrations.AlterField(
            model_name='companystatemachine',
            name='preprocess_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SIMPLE', 'Simple Prompt'), ('COMPLEX', 'Use Preprocess Bot')], default='NONE', help_text="Choose how this stage should be preprocessed: 'Simple Prompt' lets you define a direct prompt, 'Use Preprocess Bot' lets you select a separate bot to handle complex logic.", max_length=100),
        ),
        migrations.AlterField(
            model_name='flow',
            name='create_story',
            field=models.CharField(choices=[('all', 'All'), ('none', 'None')], default='all', help_text='Whether to post process the story or not', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4.1', 'GPT4_1'), ('gpt-4.1-mini', 'GPT4_1-MINI'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct'), ('gpt-5.2', 'GPT_5_2'), ('gpt-5.2-pro', 'GPT_5_2_PRO'), ('gpt-5-mini', 'GPT_5_MINI')], default='gpt-4o-mini', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='postprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip Next Stage')], default='NONE', help_text='Define how to use the postprocess output.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='postprocess_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SIMPLE', 'Simple Prompt'), ('COMPLEX', 'Use Postprocess Bot')], default='NONE', help_text="Choose how this stage should be postprocessed: 'Simple Prompt' lets you define a direct prompt, 'Use Postprocess Bot' lets you select a separate bot to handle complex logic.", max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='preprocess_output_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('SKIP', 'Skip This Stage'), ('MODIFY_QUESTION', 'Modify Bot Question')], default='NONE', help_text="Define how to use the preprocess output: 'Skip' means use output to decide if stage should be skipped; 'Enrich' means use output in this stage's prompt; 'Custom' means run custom logic on the output.", max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanystatemachine',
            name='preprocess_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SIMPLE', 'Simple Prompt'), ('COMPLEX', 'Use Preprocess Bot')], default='NONE', help_text="Choose how this stage should be preprocessed: 'Simple Prompt' lets you define a direct prompt, 'Use Preprocess Bot' lets you select a separate bot to handle complex logic.", max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalflow',
            name='create_story',
            field=models.CharField(choices=[('all', 'All'), ('none', 'None')], default='all', help_text='Whether to post process the story or not', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalvoice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('GOOGLE_V1', 'GOOGLE v1 STT'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM')], default='AI4Bharat', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('GOOGLE_V1', 'GOOGLE v1 STT'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM')], default='AI4Bharat', max_length=300, null=True),
        ),
    ]
