# Generated by Django 5.2 on 2026-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0080_alter_companychat_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
